### ISSUE TITLE
Afghanistan Commerical Adm1 file missing

### ISSUE THREAD

**Issue by LaurensJN** [gem/global_exposure_model#25]
The `Exposure_Com_Afghanistan_Adm1` file is missing. As the commercial data is shown in the summary, I was wondering where the file with taxonomies is.

**Comment by CatalinaYepes** [comment]
Thank you for highlighting this. We will fix it soon!

**Comment by CatalinaYepes** [comment]
Thank you Laurens for reporting this issue. We have added the missing file.
