### ISSUE TITLE
Taxonomy questions

### ISSUE THREAD

**Issue by d3netxer** [gem/global_exposure_model#30]
These are examples I am trying to find:

MCF/LWAL+CDL/H:1/COM

MCF/LWAL+CDM/H:1/COM

However, when I search the Taxonomy glossary (https://taxonomy.openquake.org/) for either CDL or CDM no results are found

What do these mean?

**Comment by CatalinaYepes** [comment]
Hi,

Thank you for pointing out this issue. 

We need to update the [Taxonomy glossary](https://taxonomy.openquake.org/), transitioning from the current GEM Taxonomy v2.0 to v3.2, to align it with the version employed in the global exposure model.
Meanwhile, you can find the complete list of attributes in the `Taxonomy_tables_v3.2.xlsx` of this repo https://github.com/gem/gem_taxonomy.

For your specific question, Table 3 indicates:

|String | Description |
|-- | -- |
|CDL | Low code|
|CDM | Moderate code|

For clarity, we will also include the taxonomy tables v3.2 in the home README.
