### ISSUE TITLE
question on values of some of the columns in the Exposure_Adm1_Taxonomy.csv

### ISSUE THREAD

**Issue by d3netxer** [gem/global_exposure_model#34]
In the Exposure_Adm1_Taxonomy.csv within the World File there are these following columns:

ADO/E: Adobe and Earth
MUR: Masonry, unreinforced
Masonry (reinforced)
Others
RC: reinforced concrete
W: wood

May I ask what the values in these columns represent?

My initial assumption was the number of buildings, but I checked the total for Ghor, Afghanistan, but the total doesn't seem to match the total building count within the region/country folder.

**Comment by CatalinaYepes** [comment]
Thank you @d3netxer for reporting this issue.

The value represented in the columns is the building counts per country (and the material `Masonry` includes confined and reinforced masonry).
Thanks to this post we found that the values reported in the `Exposure_Adm1_Taxonomy.csv` are twice the actual values. We will correct the summary files ASAP.
